### ISSUE TITLE
dm-webservice is not deploying our changes

### ISSUE THREAD

**Issue by ykowsar** [gvlproject/genomespace#1]
Look at MountedFileProviderManagerImpl class. The two swiftlogger calls will never happen.

It might be worth sending a request to Marko about this.

**Comment by ykowsar** [comment]
**MountedFileProviderManager** class is a bean initialised through dm-core.xml using bean id **configuredProviderManager**

Everything should happen through dm-webservice.xml
the qualifier makes spring goes to the associated xml file and initialise the object using the constructor-arg as input argument.

**Comment by madisonkeene** [comment]
log statement now works, and shows that its picking up changes in that .xml file - so issue must lie when its adding a provider or getting the provider

**Comment by madisonkeene** [comment]
Two things:
1. There is a new component under 
   `dm-webservice/src/main/java/org/genomespace/datamanager/config` 
   Needed to add the `register(SwiftStorageSpecResource.class);` line to `DataManagerWebServiceApplication.java`
2. I deleted everything in $TOMCAT_HOME/webapps **(except ROOT)** then re-compiled because something somewhere was being cached (i think the `DataManagerWebServiceApplication.class` file)
