### ISSUE TITLE
the path shown on the top of the page is not correct

### ISSUE THREAD

**Issue by ykowsar** [gvlproject/genomespace#12]
This is the cause of many other errors like deleting inside a directory see attached
![screen shot 2016-07-01 at 11 50 09 am](https://cloud.githubusercontent.com/assets/8486816/16509700/dbe1c370-3f82-11e6-98bc-6415eeae82ed.png)

**Comment by madisonkeene** [comment]
global variable.....

**Comment by madisonkeene** [comment]
likely that this is causing #13 #15 #8

**Comment by madisonkeene** [comment]
There are issues with gsFileMetadata of some kind - this is where the incorrect path is coming from

**Comment by madisonkeene** [comment]
GSFileMetadata seems to be correct, based off GET request for https://newgs-test3.ddns.net:8443/datamanager/v1.0/filemetadata/Home/swift:test/test2/MRSA0252.fna

**Comment by madisonkeene** [comment]
Metadata for directories is incorrect - GET request - https://newgs-test3.ddns.net:8443/datamanager/v1.0/file//Home/swift:test/test2/

**Comment by madisonkeene** [comment]
This bug is driving me up the wall !!!!!!!!

**Comment by madisonkeene** [comment]
Path now correct. DisplayPath still incorrect

**Comment by madisonkeene** [comment]
![Screen Shot 2016-07-07 at 3.59.40 PM.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Screen%20Shot%202016-07-07%20at%203.59.40%20PM-8135416d0f489bc6a2f891c6eae5323903ae0bac841d7aec747e31b44b4e925e.png)

winner winner chicken dinner

**Comment by madisonkeene** [comment]
Issue: `GSDirectoryListing` has 2 sections:
1. `GSFileMetadata` for the directory you are listing
2. a set of `GSFileMetadata` objects, 1 for each file inside directory

The `GSFileMetadata` for the directory being listed was always being set to the GSFileMetadata for `swift:<container>` instead of `<subdirectory>`

changes:
- `buildGsRootMetadata()` (SwiftUtils.java:177) - removed the `SWIFT_PREFIX` from here, and put it directly in front of the container name in `buildSwiftDirectoryListing()` (SwiftFileSystemProvider.java:222). Also make sure `buildSwiftDirectoryListing()` will send the right path to `buildGsRootMetadata()` (i.e. container path or sub dir path)
