### ISSUE TITLE
Bug on renaming file

### ISSUE THREAD

**Issue by alonie** [gvlproject/genomespace#28]
Rename file: didn't seem to work (at least there is no visual evidence of it working, although the dialogue boxes all do the right thing). Then, refreshing parent folder, got error 'HTTP Status 500 - Command exception, HTTP Status code: 404 => ENTITY_DOES_NOT_EXIST'. 
However it then seemed to have worked, and then the file had been renamed. Huh.

**Comment by madisonkeene** [comment]
This happens when users refresh the swift container while its in the middle of the rename, which for swift, is actually a copy and delete. If no refresh is done it succeeds without error. Need to discuss with broad - they should add something to catch these status 500 errors so they're not so ugly and kick users out to the homepage. or have an option for users to report errors or something.

**Comment by madisonkeene** [comment]
Now in issue #37
