### ISSUE TITLE
Dropbox uploads broken - CORS issue.

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/genomespace#45]
XMLHttpRequest cannot load https://genomespace-test-dev.s3.amazonaws.com/tmp/2016-09-09%2003%3A41%3A01%3A31_bitOps.java?uploads. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://genomespace-dev.genome.edu.au' is therefore not allowed access. The response had HTTP status code 403.

**Comment by madisonkeene** [comment]
Same thing is happening for google drive.

**Comment by madisonkeene** [comment]
@ykowsar I think this is a AWS config issue (but I have no credentials to get in and check).

**Comment by nuwang** [comment]
@madiflannery @ykowsar Which account are you using for the new GenomeSpace? Andrew really wanted to consolidate our two accounts into one, and the plan was to migrate GenomeSpace to the 326******9 account. (We have another account that starts with 8 or 9 as I recall, which was used by GenomeSpace - and needs to be closed down). Madi, I've just sent you credentials for accessing the dashboard.

**Comment by madisonkeene** [comment]
OK no worries. Not sure which acct we're using but I'll make sure it all gets migrated over to the new one :)

**Comment by ykowsar** [comment]
The whole thing is broken. In response for uploading something to dropbox genomespace assume it is an s3 storage type and since there is no s3 associated with this name it returns the address to the home directory which I have made it readonly.

I cannot find why it assume it is an s3 account this but this is what we should fix. Here is a sample response for uploading to dropbox:
"uploadType":"S3","path":"\/storage\/System\/s3\/genomespace-dev\/tmp\/2016-09-13 08:52:33:413_BucketExplorer.dmg","s3BucketName":"genomespace-dev" ....

And it is clear the uploadType is wrong

**Comment by madisonkeene** [comment]
I have a funny feeling this is a merge-gone-wrong thing - will investigate! Thanks @ykowsar :)

**Comment by nuwang** [comment]
@ykowsar @madiflannery I ran into this issue on the U.S genomespace server - I think it's by design. That is, although the uploadType is s3, if you upload to the given URL, it will go into the dropbox folder - so I'm guessing that GenomeSpace is now using S3 as a temporary staging area before uploading to dropbox.

**Comment by madisonkeene** [comment]
Hmmmm very interesting - we should investigate how much $$$ this will cost and what we need to do  @ykowsar

**Comment by madisonkeene** [comment]
Yep, you're completely correct @nuwang 

An upload to dropbox on gs.org: 
![Screen Shot 2016-09-14 at 3.47.00 PM.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Screen%20Shot%202016-09-14%20at%203.47.00%20PM-4f5e94729fcc464bf932ac2d559ba98bd082f26ae856deab2b8e4ccf6e5f0370.png)

**Comment by madisonkeene** [comment]
OK So here's the deal:
- Broad added a new section under dm-core called 'tempstorage', and they magically proxy uploads through the default s3 bucket via an object called TempStorageSystemProvider. When the uploadInfo is created, they call a method called `tempStorageProvider.generateTempUploadInfo(dropboxFileId, remainingQuota);`
- I imagine this will cost us money as we're doing requests to the s3 bucket.
- I've successfully un-done the Dropbox upload going via this mechanism, uploads are working fine on the merge machine (just have to port changes over to the gs-dev machine). TO do that I basically had to change the DropboxUploadInfo object back to what it was before they implemented the temp storage thing. 
- The bad news: there's no version of GoogleDriveUploadInfo that existed before they implemented temp storage.... so I can't reset that one.

I'm voting the way forward is to change dropbox back to not go via s3, get s3 uploads working, and disable google drive for now. That way we can give the CDK to neil/wilson, they can get a sepsis demo working using swift/dropbox/s3, then worry about pushing out a gdrive upload info that doesn't use s3, and re-enabling gdrive after that. Thoughts @ykowsar @nuwang @AndrewIsaac ?

**Comment by madisonkeene** [comment]
p.s- this is the worst thing EVER

**Comment by ykowsar** [comment]
That is a stupid rediculous and retarded way to manage an upload I am very
surprised 🤐

**Comment by nuwang** [comment]
But won't that mean diverging from the U.S. codebase? I think it makes sense to have the code be consistent with whatever the U.S. GenomeSpace server is doing. There must have been a reason for using a temp staging area - maybe Marco or Ted will be able to provide specifics. From an SDK point of view, it does make the implementation simpler because you don't have to have specialised handling for each type of storage (e.g. dropbox and google drive) - everything is an s3 upload.

**Comment by ykowsar** [comment]
No the way they have handle this is too simolistic which is unwanted here.
Using s3  means a huge cost and still you have to handle every upload on
the server side which is the same as having a client side upload. And up to
what I have seen now every objectstore has a post mechanism upload

**Comment by madisonkeene** [comment]
It will mean diverging, yes, but the alternative is that it costs us money every time a user uploads to any storage type... This is probably a decision that needs to be made by the higher ups imo cause its not 100% clear what is happening to GS Australia going forward - if its not going to exist in a few months time then it doesn't really matter what we do to the code base.

**Comment by ykowsar** [comment]
There are more issue than just the cost. They are basically bridging the SLA.

**Comment by madiflannery** [comment]
Yeah that too haha. Really need to get this out though...

**Comment by ykowsar** [comment]
Why do we need to provide dropbox or google drive on the local server in
the first place? They are so out of scope for our project to me.

On Thu, Sep 15, 2016 at 11:17 AM, Madison Flannery <notifications@github.com

**Comment by madisonkeene** [comment]
Because that's what was promised for sepsis- not all users will have swift access

**Comment by nuwang** [comment]
If we end up using the u.s
Genomespace (which we should imo), cost is a non issue because it'll be handled by broad. I believe the reason it has been done this way is so that you can add new types of storage without breaking existing clients. For example, the python- genomespaceclient didn't have support for Dropbox, but it works with Dropbox anyway.

If, on the other hand, they shifted the burden of handing storage types to the client, that would be a bad design decision because existing clients would keep breaking every time a new storage type is added - not exactly a good client-server design.

So i think what they've done is logical and as long as the cost is a non issue for them, it should eventually be a non issue for us post-merge.

**Comment by madisonkeene** [comment]
This looks like it's only for small uploads though - if you have a client you'd still have to manage the large uploads for each storage type afaik.

I agree we should move to the US GS, but the problem is that neil/wilson need a new and updated GS Australia (with swift) to point the new CDK at - and this really needs to happen in the next day or two. All good though, I'll get clarification on what we should do from @AndrewIsaac and then go from there :)

**Comment by nuwang** [comment]
The most elegant thing would have been to have a storage independent upload endpoint. Internally, Genomespace could have potentially done an async upload to the actual storage. Doing something like that can get pretty complicated though. Using s3 is the simpler solution because all existing clients support s3.

**Comment by madisonkeene** [comment]
Yeah that'd definitely be the most elegant solution! All good though it is what it is

**Comment by nuwang** [comment]
@madiflannery only small uploads? Then none of what I thought makes sense if you end up having to handle different storage types on the client anyway :-(

**Comment by madisonkeene** [comment]
I'm not 100% sure but I am still seeing multipart upload code randomly throughout the code base, but I havent really paid attention to what data type its for... will have to investigate!

**Comment by ykowsar** [comment]
That is exactly when you are breaking the SLA. Imagine I have a patient
data and I am only able to upload it to a specific place which the patient
agreed and I am trying to use GenomeSpace. Now genomespace is uploading my
data to a storage without letting me know and bridge my agreement with
patient or government or many other organizations which is a crappy
mechanism :) I am not sure even my data remains in Australia or going
overseas now.

**Comment by madisonkeene** [comment]
OK this whole thing is so weird. So when I upload to dropbox, it basically puts the file in a tmp folder in the default s3 bucket, and then its not actually in my dropbox, though i can see it as though it is in my GS

**Comment by ykowsar** [comment]
I hope not maybe we should have a chat with Marco on this. This can be a
big issue.

**Comment by madisonkeene** [comment]
Emailing Ted and Marco as we speak - the file I uploaded from their GS yesterday is in my dropbox so I feel like we're missing something. Will cc you.

**Comment by ykowsar** [comment]
I mean I hope everything is handled on client side. Yes the file would
eventually get to your dropbox but it is important how it gets into your
dropbox. Are they uploading it first to a temp folder on Amzon or not?

**Comment by madisonkeene** [comment]
Yeah but it's not going to my dropbox at the moment at all - its staying inside the tmp folder. I can tell because all of my CDK test uploads from the last week are still in there....

**Comment by madisonkeene** [comment]
But yes can confirm it is most definitely going via an s3 temp folder - @AndrewIsaac has OK'd this for gs-dev so we can use it for sepsis demo's

**Comment by ykowsar** [comment]
If that's the case we should have a clear chat about this in a meeting.
Specially with Andrew L. Many people didn't even try genomespace for these
possible scenarios a couple of years ago (Back then it was not even like
this at all). Privacy is a real concern here. And we should make sure we
are consistent with the deliverables of sepsis.

**Comment by madisonkeene** [comment]
Agreed - I've emailed broad now, cc'd you, feel free to elaborate on the privacy concerns!

**Comment by madisonkeene** [comment]
The CORS issue is now fixed.

**Comment by nuwang** [comment]
@ ykowsar interesting point about the data going overseas. can Genomespace provide that kind of SLA? Even if the actual data doesn't go overseas, the keys for accessing the data are stored in GS. One obvious difference is that keys can be revoked.

 If storing keys remotely is ok, then the solution to that upload problem could be to proxy the network connection through genomespace without hitting disk/ going through tmp storage. This would still allow for a storage independent mechanism without breaking clients and without data being stored overseas.

**Comment by ykowsar** [comment]
Unfortunately it has not been decided yet on storing keys so genomespace is
not storing the key yet. For dropbox it is using oauth2 thus it should not
even try to touch the files. I am not sure even normal people who are aware
of that be ok with that.

**Comment by madisonkeene** [comment]
Going to disable gdrive & dropbox in the UI so we can get a new GS out the door, then decide on a fix later.

Disabled by commenting out the `openMountGoogleDriveDialog();` and `openMountDropboxDialog();` calls, replacing with a 'coming soon' alert(). Closing this issue.

**Comment by madisonkeene** [comment]
(Madi will also document this issue in the GS documentation)
